spring.application.name=posts-service
server.port=9010
server.servlet.context-path=/api/v1/posts
spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.datasource.username=postgres
spring.datasource.password=122003
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
